const dummyBlocks = [
  {
    id: 0,
    owner: "bh2980",
    category: "Love",
    image: null,
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content:
      "Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.Paragraphs are the building blocks of papers. Without well-written paragraphs that flow logically from one idea to the next and that inform and help support in some meaningful way the central research problem being investigated, your paper will not be viewed as credible with the idea that transitions may be needed between paragraphs or sections in a paper. Sometimes they are also helpful within the body of a single paragraph. Within a paragraph, transitions are often single words or short phrases that help to establish relationships between ideas and to create a logical progression of those ideas in a paragraph. This is especially true within paragraphs that discuss multiple examples or discuss complex ideas, issues, or concepts. Arnaudet, Martin L. and Mary Ellen Barrett. Paragraph Development: A Guide for Students of English. 2nd edition. Englewood Cliffs, NJ: Prentice Hall Regents, 1990; Paragraph Development: Importance of Constructing Good Paragraphs. AP English Literature and Composition. Edublogs, 2012; Paragraphing. Centre for Applied Linguistics. University of Warwick.",
    likeCount: 0,
    voteIndex: 1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 1,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 2,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 3,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 4,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 5,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 6,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 7,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 8,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 9,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 10,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 11,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 12,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 13,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 14,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 15,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 16,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 17,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 18,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 19,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
  {
    id: 20,
    owner: "bh298",
    category: "Fashion",
    image: "http://localhost:8000/media/uploads/logo192_14PYWuv.png",
    createdAt: "2022-05-01T16:22:16.305148+09:00",
    updatedAt: "2022-05-01T16:22:16.305148+09:00",
    content: "Test1",
    likeCount: 0,
    voteIndex: -1,
    voteText: '[["항목1", 0], ["항목2", 0]]',
  },
];

export default dummyBlocks;
